version: '3.1'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_intranet
    restart: always
    volumes:
      - ./www/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password1234
      WORDPRESS_DB_NAME: db_intranet
      WORDPRESS_TABLE_PREFIX: dx36fd_
    ports:
      - 8585:80
    networks:
      - wp_network
  db:
    image: mariadb:latest
    container_name: wp_db
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
    networks:
      - wp_network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    ports:
      - 8686:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password1234
    networks:
      - wp_network
networks:
  wp_network:
volumes:
  db_data: